### PR TITLE
Changed user setup to one line as per requested. Changed code accordi…

### LINKED ISSUE #138: Negative values not checked
Negative input for fields like height and weight are accepted, which does not make sense.

<hr><sub>[original: aquohn/ped#2]<br/>
</sub>

### LINKED ISSUE #140: Prompt does not match input requested
If erroneous input is given and rejected, the subsequent prompt will be for the next input, but the system will only accept inputs for the current field.

<hr><sub>[original: aquohn/ped#4]<br/>
</sub>

### LINKED ISSUE #159: Invalid Prompt when given wrong input
I believe the second prompt should be input age as the original input is invalid.

Second prompt should be input height

Last prompt should be input gender

May cause confusion to users as the input "Male" may not work on the question "Input Gender"

<hr><sub>[original: Greatnest/ped#1]<br/>
</sub>

### LINKED ISSUE #160: Invalid input accepted by program during sign up
Seems that value 0 is accepted as an input? I think value should be set to 1 to 5 with an error message given for other input

<hr><sub>[original: Greatnest/ped#2]<br/>
</sub>

### LINKED ISSUE #179: Takes in incorrect input without throwing error at the beginning of programme
<hr><sub>[original: aarushisingh1/ped#1]<br/>
</sub>

### PR DESCRIPTION
**Pull request by koushireo**
Changed user setup to one line as per requested. Changed code according to Hashir's specification. Closes #160, closes #159 , closes #179, closes #138 and closes #140. Created unused code folder for us to throw our unused code.

### CODE REVIEW

File: src/main/java/duke/logic/commands/UpdateWeightCommand.java [hunk 1]
```diff
@@ -66,20 +66,27 @@ public void stage0(User user, Storage storage) {
         ui.showLine();
         HashMap<LocalDate, Double> allWeight = user.getAllWeight();
         if (!allWeight.containsKey(currentDate)) {
-            try {
-                user.setWeight(Integer.parseInt(weight), currentDate);
-                ui.showWeightUpdate(user, Integer.parseInt(weight), currentDate);
-                ui.showLine();
-            } catch (NumberFormatException e) {
-                ui.showMessage("Please input a proper number for weight");
+            if (Integer.parseInt(weight) > 2) {
```
Comment (GaryStu) [inline src/main/java/duke/logic/commands/UpdateWeightCommand.java]: For better code quality, you can use guard clauses to check for invalid lines first.

File: src/main/java/duke/logic/commands/UserSetup.java [hunk 2]
```diff
@@ -27,57 +30,55 @@ public void start() {
...
-            setName(info);
-        } else if (user.getAge() == 0) {
-            int age = 0;
-            try {
-                age = in.getInt();
-            } catch (Exception e) {
-                ui.showMessage(e.getMessage());
-            }
-            setAge(age);
+        HashMap<String, String> temp = ArgumentSplitter.splitForwardSlashArguments(info);
```
Comment (GaryStu) [inline src/main/java/duke/logic/commands/UserSetup.java]: maybe get a better name than temp
